### ISSUE TITLE
itext_iterator lacks support for operator->

### ISSUE THREAD

**Issue by tahonermann** [tahonermann/text_view-range-v3#1]
Range-v3's basic_iterator does not currently provide operator->; the cursor arrow() member function specified in P0186 and supported by cmcstl2 is not honored.

**Comment by tahonermann** [comment]
A pull request providing support for operator-> was recently submitted by Casey:
- https://github.com/ericniebler/range-v3/pull/544

**Comment by tahonermann** [comment]
Workaround checked in via commit df96b878cea65a8ca0760ddfc081b9cd6f4ccb20.

**Comment by CaseyCarter** [comment]
> A pull request providing support for `operator->` was recently submitted by Casey

I'm about halfway through updating range-v3's `basic_iterator` to agree with cmcstl2's.

**Comment by tahonermann** [comment]
> I'm about halfway through updating range-v3's basic_iterator to agree with cmcstl2's.

Woo hoo!  Thanks @CaseyCarter!
