### ISSUE TITLE
The range-v3 Writable iterator concept requires operator= to return non-void

### ISSUE THREAD

**Issue by tahonermann** [tahonermann/text_view-range-v3#4]
This issue was exposed by the implementation of output_iterator in test/test-text_view.cpp; its operator= definition returned void as permitted by the standard.  The range-v3 implementation of the Writable iterator concept requires operator= to return non-void, presumably unintentionally.

**Comment by tahonermann** [comment]
Workaround checked in via commit 0b2ba0e92711c7a850579b5159885a23ac6cd252.

**Comment by CaseyCarter** [comment]
I fixed this a couple of weeks ago in caseycarter/range-v3@c41227ff1efaa31573f8d8c8b90fca4b34d294dd, which Eric just merged to master this morning.
